name = "emu6502"
description = "Emu6502"
version = "0.1.0-dev"

authors = ["Frederic Bousquet"]
maintainers = ["Frederic Bousquet <bousquetfrederic@outlook.fr>"]
maintainers-logins = ["bousquetfrederic"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

executables = ["emu6502"]

[[depends-on]]
json = "^6.0.0"
